apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-github-issues
  namespace: rhdh
  title: "GitHub Issues"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/github-issues
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/github-issues
  tags: []
spec:
  packageName: "@backstage-community/plugin-github-issues"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-github-issues:bs_1.45.3__0.16.0!backstage-community-plugin-github-issues
  version: 0.16.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - github-issues
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-github-issues:
              mountPoints:
                - mountPoint: entity.page.issues/cards
                  importName: GithubIssuesCard
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      allOf:
                        - hasAnnotation: github.com/project-slug
