apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-ocm
  namespace: rhdh
  title: OCM Frontend
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://github.com/backstage/community-plugins/issues
    title: Bugs
  - title: Source Code
    url: https://github.com/backstage/community-plugins/tree/main/workspaces/ocm
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/ocm
  tags: []
spec:
  packageName: '@backstage-community/plugin-ocm'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-ocm
  version: 5.11.1
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: production
  lifecycle: deprecated
  partOf:
  - openshift-cluster-manager
  appConfigExamples:
  - title: Default configuration
    content:
      dynamicPlugins:
        frontend:
          backstage-community.plugin-ocm:
            appIcons:
            - name: ocmIcon
              importName: OcmIcon
            dynamicRoutes:
            - path: /ocm
              importName: OcmPage
              menuItem:
                icon: ocmIcon
                text: Clusters
                textKey: menuItem.clusters
            mountPoints:
            - mountPoint: entity.page.overview/context
              importName: ClusterContextProvider
            - mountPoint: entity.page.overview/cards
              importName: ClusterAvailableResourceCard
              config:
                layout:
                  gridColumnEnd:
                    lg: span 4
                    md: span 6
                    xs: span 12
                if:
                  allOf:
                  - isKind: resource
                  - isType: kubernetes-cluster
            - mountPoint: entity.page.overview/cards
              importName: ClusterInfoCard
              config:
                layout:
                  gridColumnEnd:
                    lg: span 4
                    md: span 6
                    xs: span 12
                if:
                  allOf:
                  - isKind: resource
                  - isType: kubernetes-cluster
