apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-announcements
  namespace: rhdh
  title: Announcements
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/announcements
  tags: []
spec:
  packageName: "@backstage-community/plugin-announcements"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-announcements:bs_1.45.3__1.1.0!backstage-community-plugin-announcements
  version: 1.1.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Backstage Community
  support: community
  lifecycle: active
