#!/usr/bin/env bash
# Post-script: push the fix agent's branch and create a cross-fork PR.
#
# Runs on the host AFTER the sandbox is destroyed. The extracted target repo
# (with the agent's commits) is at REPO_DIR.
#
# Required environment variables:
#   GH_TOKEN        — token with repo scope on fork + upstream
#   REPO_FULL_NAME  — upstream owner/repo (e.g. redhat-developer/rhdh-plugin-export-overlays)
#   FORK_FULL_NAME  — fork owner/repo (e.g. subhashkhileri/rhdh-plugin-export-overlays)
#
# Optional:
#   FIX_PR_BRANCH   — if set, the agent added commits to an existing branch
#   REPO_DIR        — path to extracted repo (default: current directory)
set -euo pipefail

REPO_DIR="${REPO_DIR:-$(pwd)}"
cd "${REPO_DIR}"

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${REPO_FULL_NAME:?REPO_FULL_NAME is required}"
: "${FORK_FULL_NAME:?FORK_FULL_NAME is required}"

export GH_TOKEN

FORK_OWNER="${FORK_FULL_NAME%%/*}"

# ---------------------------------------------------------------------------
# 1. Verify feature branch
# ---------------------------------------------------------------------------
BRANCH="$(git branch --show-current)"

if [ -z "${BRANCH}" ] || [ "${BRANCH}" = "main" ] || [ "${BRANCH}" = "master" ]; then
  echo "Agent did not create a feature branch (current: '${BRANCH:-detached HEAD}') — nothing to push"
  exit 0
fi

CHANGED_FILES="$(git diff --name-only HEAD~1..HEAD 2>/dev/null || true)"
if [ -z "${CHANGED_FILES}" ]; then
  echo "No changed files in agent's commit — nothing to push"
  exit 0
fi

echo "Branch: ${BRANCH}"
echo "Changed files:"
echo "${CHANGED_FILES}" | sed 's/^/  /'

# ---------------------------------------------------------------------------
# 2. Set up fork remote
# ---------------------------------------------------------------------------
if ! git remote get-url fork >/dev/null 2>&1; then
  git remote add fork "https://x-access-token:${GH_TOKEN}@github.com/${FORK_FULL_NAME}.git"
else
  git remote set-url fork "https://x-access-token:${GH_TOKEN}@github.com/${FORK_FULL_NAME}.git"
fi

# ---------------------------------------------------------------------------
# 3. Push to fork
# ---------------------------------------------------------------------------
echo "Pushing ${BRANCH} to ${FORK_FULL_NAME}..."
if ! git push -u fork "${BRANCH}" 2>&1; then
  echo "Plain push failed — retrying with --force-with-lease"
  git push --force-with-lease -u fork "${BRANCH}" 2>&1
fi

# ---------------------------------------------------------------------------
# 4. Create or update PR
# ---------------------------------------------------------------------------
EXISTING_PR="$(gh pr list --repo "${REPO_FULL_NAME}" \
  --head "${FORK_OWNER}:${BRANCH}" \
  --state open --json number,url --jq '.[0]' 2>/dev/null || true)"

if [ -n "${EXISTING_PR}" ] && [ "${EXISTING_PR}" != "null" ]; then
  PR_URL="$(echo "${EXISTING_PR}" | jq -r '.url')"
  PR_NUM="$(echo "${EXISTING_PR}" | jq -r '.number')"
  echo "PR #${PR_NUM} already exists — updated with new commits"
  echo "PR: ${PR_URL}"
  exit 0
fi

echo "Creating cross-fork PR..."

COMMIT_SUBJECT="$(git log -1 --format='%s' HEAD)"
COMMIT_BODY="$(git log -1 --format='%b' HEAD | sed -e :a -e '/^\n*$/{ $d; N; ba; }')"

PR_BODY="${COMMIT_BODY:-Automated E2E fix.}

---
Generated by fullsend analysis → fix pipeline."

PR_URL="$(gh pr create \
  --repo "${REPO_FULL_NAME}" \
  --head "${FORK_OWNER}:${BRANCH}" \
  --base "main" \
  --title "${COMMIT_SUBJECT}" \
  --body "${PR_BODY}" \
  2>&1)"

echo "PR created: ${PR_URL}"
