apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-orchestrator
  namespace: rhdh
  title: Orchestrator Frontend
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should
        raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator
  tags:
    - automation
spec:
  packageName: '@red-hat-developer-hub/backstage-plugin-orchestrator'
  # Tag: 1.10.0--5.4.1, Build date: 2026-01-29T16:08:22Z
  dynamicArtifact: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-b\
    ackstage-plugin-orchestrator@sha256:f40d39fb7599d2cbfa8f64d6f4703d69539e4a4\
    b0e49518499f47ca986fbd814"
  version: 5.7.4
  backstage:
    role: frontend-plugin
    supportedVersions: 1.49.3
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - orchestrator
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-orchestrator:
              appIcons:
                - importName: OrchestratorIcon
                  name: orchestratorIcon
              dynamicRoutes:
                - importName: OrchestratorPage
                  menuItem:
                    icon: orchestratorIcon
                    text: Orchestrator
                    textKey: menuItem.orchestrator
                  path: /orchestrator
              entityTabs:
                - path: /workflows
                  title: Workflows
                  titleKey: catalog.entityPage.workflows.title
                  mountPoint: entity.page.workflows
              mountPoints:
                - mountPoint: entity.page.workflows/cards
                  importName: OrchestratorCatalogTab
                  config:
                    layout:
                      gridColumn: 1 / -1
                      if:
                        anyOf:
                          - IsOrchestratorCatalogTabAvailable
