apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-orchestrator
  namespace: rhdh
  title: Orchestrator Frontend
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://issues.redhat.com/browse/RHDHBUGS
    title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
  - title: Source Code
    url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator
  tags:
  - automation
spec:
  packageName: '@red-hat-developer-hub/backstage-plugin-orchestrator'
  # Tag: 1.10.0--5.4.0, Build date: 2026-01-29T16:08:22Z
  dynamicArtifact: "oci://quay.io/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator@sha256:03052706c1e59d1cbb634a80c5fb236417148657320265dd0ed59988b3bb9307"
  version: 5.4.1
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
  - orchestrator
  appConfigExamples:
  - title: Default configuration
    content:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-orchestrator:
            appIcons:
            - importName: OrchestratorIcon
              name: orchestratorIcon
            dynamicRoutes:
            - importName: OrchestratorPage
              menuItem:
                icon: orchestratorIcon
                text: Orchestrator
                textKey: menuItem.orchestrator
              path: /orchestrator
            entityTabs:
            - path: /workflows
              title: Workflows
              titleKey: catalog.entityPage.workflows.title
              mountPoint: entity.page.workflows
            mountPoints:
            - mountPoint: entity.page.workflows/cards
              importName: OrchestratorCatalogTab
              config:
                layout:
                  gridColumn: 1 / -1
                  if:
                    anyOf:
                    - IsOrchestratorCatalogTabAvailable
