apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: redhat-backstage-plugin-orchestrator-backend-module-loki
  namespace: rhdh
  title: "Orchestrator Backend Module Loki"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHIDP
      title: Bugs
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-backend-module-loki
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/orchestrator/plugins/orchestrator-backend-module-loki
  tags:
    - automation
spec:
  packageName: "@red-hat-developer-hub/backstage-plugin-orchestrator-backend-module-loki"
  # Tag: 1.10.0--1.0.1, Build date: 2026-04-20T22:08:14Z
  dynamicArtifact: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend-module-loki@sha256:d5970c0e63d43162fa77f342a76b3bffbe54fe6cbabc56335ea11ecaa74591c4"
  version: 1.2.4
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.49.3
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - orchestrator
  appConfigExamples:
    - title: Default configuration
      content:
        orchestrator:
          workflowLogProvider:
            loki:
              baseUrl: ${LOKI_BASE_URL}
