apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-catalog-backend-module-pingidentity
  namespace: rhdh
  title: "Catalog Backend Module PingIdentity"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/pingidentity
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/pingidentity
  tags:
    - software-catalog
spec:
  packageName: "@backstage-community/plugin-catalog-backend-module-pingidentity"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-pingidentity-dynamic
  version: 0.9.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.45.3
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - pingidentity
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            pingIdentityOrg: {}
