apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: red-hat-developer-hub-backstage-plugin-bulk-import
  namespace: rhdh
  title: Bulk Import Frontend
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://issues.redhat.com/browse/RHDHBUGS
    title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
  - title: Source Code
    url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/bulk-import
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/bulk-import
  tags: []
spec:
  packageName: '@red-hat-developer-hub/backstage-plugin-bulk-import'
  dynamicArtifact: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
  version: 7.0.1
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
  - bulk-import
  appConfigExamples:
  - title: Default configuration
    content:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-bulk-import:
            translationResources:
            - importName: bulkImportTranslations
              module: Alpha
              ref: bulkImportTranslationRef
            appIcons:
            - name: bulkImportIcon
              importName: BulkImportIcon
            dynamicRoutes:
            - path: /bulk-import
              importName: BulkImportPage
              menuItem:
                icon: bulkImportIcon
                text: Bulk import
                textKey: menuItem.bulkImport
