apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: pagerduty-backstage-plugin
  namespace: rhdh
  title: "PagerDuty Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/PagerDuty/backstage-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/PagerDuty/backstage-plugins/tree/main/plugins/backstage-plugin
  annotations:
    backstage.io/source-location: url:https://github.com/PagerDuty/backstage-plugins/tree/main/plugins/backstage-plugin
  tags: []
spec:
  packageName: "@pagerduty/backstage-plugin"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/pagerduty-backstage-plugin:bs_1.45.3__0.16.4!pagerduty-backstage-plugin
  version: 0.16.4
  backstage:
    role: frontend-plugin
    supportedVersions: 1.42.5
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - pagerduty
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            pagerduty.backstage-plugin:
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: EntityPagerDutyCard
                  config:
                    layout:
                      gridColumnEnd:
                        md: span 6
                        xs: span 12
                    if:
                      allOf:
                        - isPluginApplicableToEntity
