apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-jenkins-backend
  namespace: rhdh
  title: "Jenkins Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins
  tags: []
spec:
  packageName: "@backstage-community/plugin-jenkins-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-jenkins-backend:bs_1.45.3__0.22.0!backstage-community-plugin-jenkins-backend
  version: 0.22.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - jenkins
  appConfigExamples:
    - title: Default configuration
      content:
        jenkins:
          instances:
            - name: default
              baseUrl: ${JENKINS_URL}
              username: ${JENKINS_USERNAME}
              apiKey: ${JENKINS_TOKEN}
