apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-topology
  namespace: rhdh
  title: Topology
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://issues.redhat.com/browse/RHIDP
    title: Bugs
  - title: Source Code
    url: https://github.com/backstage/community-plugins/tree/main/workspaces/topology
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/topology
  tags: []
spec:
  packageName: '@backstage-community/plugin-topology'
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-topology
  version: 2.9.4
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
  - topology
  appConfigExamples:
  - title: Default configuration
    content:
      dynamicPlugins:
        frontend:
          backstage-community.plugin-topology:
            translationResources:
            - importName: topologyTranslations
              ref: topologyTranslationRef
              module: Alpha
            mountPoints:
            - mountPoint: entity.page.topology/cards
              importName: TopologyPage
              config:
                layout:
                  gridColumn: 1 / -1
                  height: 75vh
                if:
                  anyOf:
                  - hasAnnotation: backstage.io/kubernetes-id
                  - hasAnnotation: backstage.io/kubernetes-namespace
