# yaml-language-server: $schema=https://raw.githubusercontent.com/redhat-developer/rhdh-plugins/refs/heads/main/workspaces/extensions/json-schema/packages.json
apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: cost-management-backend
  namespace: rhdh
  title: "Cost Management Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://issues.redhat.com/browse/RHDHBUGS
      title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
    - title: Source Code
      url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/cost-management
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/cost-management
  tags:
    - cost-management
    - optimization
    - insights
    - openshift
spec:
  packageName: "@red-hat-developer-hub/plugin-cost-management-backend"
  dynamicArtifact: oci://quay.io/redhat-resource-optimization/dynamic-plugins:2.0.2!red-hat-developer-hub-plugin-cost-management-backend
  version: 2.1.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: dev-preview
  lifecycle: active
  partOf:
    - cost-management
  appConfigExamples:
    - title: Default configuration
      content:
        proxy:
          endpoints:
            '/cost-management/v1':
              target: https://console.redhat.com/api/cost-management/v1
              allowedHeaders: [ 'Authorization' ]
              credentials: dangerously-allow-unauthenticated
        costManagement:
          clientId: ${CM_CLIENT_ID}
          clientSecret: ${CM_CLIENT_SECRET}
