apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-analytics-provider-segment
  namespace: rhdh
  title: "Analytics Provider Segment"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/analytics
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/analytics
  tags: []
spec:
  packageName: "@backstage-community/plugin-analytics-provider-segment"
  # Tag: bs_1.54.6__1.31.1, Build date: 2026-05-22T15:13:27Z
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-analytics-provider-segment@sha256:e61fa2943258fa01e3c9aa762f5c33ff76de92f322a563b48bed68111905e8f6"
  version: 1.31.1
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - analytics-provider-segment
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-analytics-provider-segment:
              analyticsApiExtensions:
                - importName: SegmentAnalytics
        backend:
          csp:
            script-src:
              - "'self'"
              - "'unsafe-eval'"
              - https://cdn.segment.com
        app:
          analytics:
            segment:
              writeKey: ${SEGMENT_WRITE_KEY}
              maskIP: true
              testMode: ${SEGMENT_TEST_MODE}
              appVersion: ${RHDH_VERSION}
              backstageVersion: ${BACKSTAGE_VERSION}
