apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-3scale-backend
  namespace: rhdh
  title: "3Scale"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/3scale
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/3scale
  tags: []
spec:
  packageName: "@backstage-community/plugin-3scale-backend"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-3scale-backend:bs_1.45.3__3.10.0!backstage-community-plugin-3scale-backend
  version: 3.10.0
  backstage:
    role: backend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - 3scale
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            threeScaleApiEntity:
              default:
                baseUrl: ${THREESCALE_BASE_URL}
                accessToken: ${THREESCALE_ACCESS_TOKEN}
