apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-signals
  namespace: rhdh
  title: "Signals Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/signals
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/signals
  tags: []
spec:
  packageName: "@backstage/plugin-signals"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-signals
  version: 0.0.25
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - signals-frontend
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-signals: {}
