apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-kubernetes-backend
  namespace: rhdh
  title: "Kubernetes Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/kubernetes-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/kubernetes-backend
  tags: []
spec:
  packageName: "@backstage/plugin-kubernetes-backend"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
  version: 0.20.4
  backstage:
    role: backend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - kubernetes
  appConfigExamples:
    - title: Default configuration
      content:
        kubernetes:
          serviceLocatorMethod:
            type: multiTenant
          clusterLocatorMethods:
            - type: config
              clusters:
                - name: ${K8S_CLUSTER_NAME}
                  url: ${K8S_CLUSTER_URL}
                  authProvider: serviceAccount
                  skipTLSVerify: true
                  serviceAccountToken: ${K8S_CLUSTER_TOKEN}
