apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-catalog-backend-module-github-org
  namespace: rhdh
  title: "Catalog Backend Module GitHub Organization"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github-org
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github-org
  tags:
    - software-catalog
spec:
  packageName: "@backstage/plugin-catalog-backend-module-github-org"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic
  version: 0.3.16
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.45.3
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
    - backstage-plugin-catalog-backend-module-github-org
  appConfigExamples:
    - title: Default configuration
      content:
        catalog:
          providers:
            githubOrg:
              id: production
              githubUrl: ${GITHUB_URL}
              orgs:
                - ${GITHUB_ORG}
              schedule:
                frequency:
                  minutes: 60
                initialDelay:
                  seconds: 15
                timeout:
                  minutes: 15
