apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-scaffolder-backend-module-azure
  namespace: rhdh
  title: "Scaffolder Backend Module Azure"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-azure
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-azure
  tags:
    - software-templates
spec:
  packageName: "@backstage/plugin-scaffolder-backend-module-azure"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-azure-dynamic
  version: 0.2.15
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.45.3
  author: Red Hat
  support: community
  lifecycle: active
  partOf:
    - azure-scaffolder-actions
  appConfigExamples: []
