apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: bcp-ctlg-backend-mod-scaffolder-relation-processor
  namespace: rhdh
  title: "Catalog Backend Module Scaffolder Relation Processor"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-relation-processor
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-relation-processor
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-catalog-backend-module-scaffolder-relation-processor"
  dynamicArtifact: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-scaffolder-relation-processor-dynamic
  version: 2.11.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.45.3
  author: Red Hat
  support: tech-preview
  lifecycle: active
  partOf:
    - scaffolder-relation-processor-catalog-integration
  appConfigExamples: []
