apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-github-pull-requests-board
  namespace: rhdh
  title: "GitHub Pull Requests Board"
  links:
    - title: Issues
      url: https://github.com/backstage/community-plugins/issues/new/choose
    - title: Plugin README
      url: https://github.com/backstage/community-plugins/blob/main/workspaces/github-pull-requests-board/plugins/github-pull-requests-board/README.md
    - title: Plugin CHANGELOG
      url: https://github.com/backstage/community-plugins/blob/main/workspaces/github-pull-requests-board/plugins/github-pull-requests-board/CHANGELOG.md
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/github-pull-requests-board/plugins/github-pull-requests-board
spec:
  packageName: "@backstage-community/plugin-github-pull-requests-board"
  dynamicArtifact: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-github-pull-requests-board:bs_1.45.3__0.12.0!backstage-community-plugin-github-pull-requests-board
  version: 0.12.0
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: DAZN
  support: community
  lifecycle: active
  # partOf:
  #   - github-pull-requests-board
  appConfigExamples:
    - title: Default configuration
      content:
        dynamicPlugins:
          frontend:
            backstage-community.plugin-pull-requests-board:
              entityTabs:
                - mountPoint: entity.page.pull-requests-board
                  path: /pull-requests-board
                  title: Pull Requests Board
              mountPoints:
                - mountPoint: entity.page.pull-requests-board/cards
                  importName: EntityTeamPullRequestsCard
                  config:
                    layout:
                      gridColumn: 1 / -1
                    if:
                      anyOf:
                        - isKind: Group
                - mountPoint: home.page/cards
                  importName: PullRequestsBoard
                  config:
                    id: github-pull-request-board
                    title: "GitHub: Pull Request Board"
                    description: A board that shows open Pull Requests and their review status
                    cardLayout:
                      width:
                        minColumns: 4
                        maxColumns: 12
                        defaultColumns: 12
                      height:
                        minRows: 4
                        maxRows: 12
                        defaultRows: 6
                    props:
                      entities: [] # Required! If not provided, the board will use the current user's repositories and team.
