apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: rhdh-bsp-quickstart
  namespace: rhdh
  title: Quickstart
  links:
  - url: https://red.ht/rhdh
    title: Homepage
  - url: https://issues.redhat.com/browse/RHDHBUGS
    title: "Report issues here. Note: Customers of Red Hat Developer Hub should raise a Red Hat support case instead."
  - title: Source Code
    url: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/quickstart
  annotations:
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/quickstart
spec:
  packageName: '@red-hat-developer-hub/backstage-plugin-quickstart'
  dynamicArtifact: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-quickstart
  version: 1.8.2
  backstage:
    role: frontend-plugin
    supportedVersions: 1.45.3
  author: Red Hat
  support: production
  lifecycle: active
  partOf:
  - quickstart
  appConfigExamples:
  - title: Default configuration
    content:
      app:
        quickstart:
        - title: Set up authentication
          titleKey: steps.setupAuthentication.title
          icon: Admin
          description: Set up secure login credentials to protect your account from unauthorized access.
          descriptionKey: steps.setupAuthentication.description
          cta:
            text: Learn more
            textKey: steps.setupAuthentication.ctaTitle
            link: https://docs.redhat.com/en/documentation/red_hat_developer_hub/latest/html/authentication_in_red_hat_developer_hub/
        - title: Configure RBAC
          titleKey: steps.configureRbac.title
          icon: Rbac
          description: Assign roles and permissions to control who can view, create, or edit resources, ensuring secure and
            efficient collaboration.
          descriptionKey: steps.configureRbac.description
          cta:
            text: Manage access
            textKey: steps.configureRbac.ctaTitle
            link: /rbac
        - title: Configure Git
          titleKey: steps.configureGit.title
          icon: Git
          description: Connect your Git providers, such as GitHub to manage code, automate workflows, and integrate with platform
            features.
          descriptionKey: steps.configureGit.description
          cta:
            text: Learn more
            textKey: steps.configureGit.ctaTitle
            link: https://docs.redhat.com/en/documentation/red_hat_developer_hub/latest/html/integrating_red_hat_developer_hub_with_github/
        - title: Manage plugins
          titleKey: steps.managePlugins.title
          icon: Plugins
          description: Browse and install extensions to add features, connect with external tools, and customize your experience.
          descriptionKey: steps.managePlugins.description
          cta:
            text: Explore plugins
            textKey: steps.managePlugins.ctaTitle
            link: /extensions
        - title: Import application
          roles:
          - developer
          icon: Import
          description: Import your existing code and services into the catalog to organize and access them through your developer
            portal.
          cta:
            text: Import
            link: /bulk-import
        - title: Learn about the Catalog
          roles:
          - developer
          icon: Catalog
          description: Discover all software components, services, and APIs, and view their owners and documentation.
          cta:
            text: View Catalog
            link: /catalog
        - title: Explore Self-service templates
          roles:
          - developer
          icon: SelfService
          description: Use our self-service templates to quickly set up new projects, services, or documentation.
          cta:
            text: Explore templates
            link: /create
        - title: Find all Learning Paths
          roles:
          - developer
          icon: Learning
          description: Integrate tailored e-learning into your workflows with Learning Paths to accelerate onboarding, close
            skill gaps, and promote best practices.
          cta:
            text: View Learning Paths
            link: /learning-paths
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-quickstart:
            translationResources:
            - importName: quickstartTranslations
              module: Alpha
              ref: quickstartTranslationRef
            mountPoints:
            - mountPoint: application/provider
              importName: QuickstartDrawerProvider
            - mountPoint: application/internal/drawer-state
              importName: QuickstartDrawerStateExposer
            - mountPoint: application/internal/drawer-content
              importName: QuickstartDrawerContent
              config:
                id: quickstart
            - mountPoint: global.header/help
              importName: QuickstartButton
              config:
                priority: 100
